name: Actions Airport
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        working-directory: ./JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: start project
        run: npm run start
      - name: unit test
        run: npm run test